### ISSUE TITLE
Nothing works except addresses about: *.

### ISSUE THREAD

**Issue by wvxwxvw** [8176135/blacklist-autoclose#1]
Let's check:
Take for example: http://sendfile.su/1557896 or any other download on this domain.
Click the "Download" button >> a link appears, if you click on it, it opens a tab with the same address as the link.
Composing regex: ^(.*)s4\.sendfile\.su\/download\/(.*)+$
Check it on https://regex101.com/
Adding it to the addon.
Return to sendfile.su and try.

Where is the promised tab closure?

**Comment by 8176135** [comment]
I can replicate it, at a guess it seems like the method the addon is using to get tab's url doesn't work for downloads. I'm having a look now.

**Comment by 8176135** [comment]
Fixed, should have an update published by tomorrow. Thanks!

However, 
> `^(.)s4.sendfile.su/download/(.)+$`

doesn't quite work, you need to be: ` ^(.*)s4.sendfile.su/download/(.)+$`. The brackets are optional.

EDIT: oh I just realized that github's markdown broke what you posted, so your original message probably works. Use the backtick ` to insert text verbatim
