### ISSUE TITLE
[Suggestion] – button to Remove current site from blacklist

### ISSUE THREAD

**Issue by Chronogram** [8176135/blacklist-autoclose#10]
Sometimes it is really hard to manually remove a site from the list. Especially if the list is long. It would be really helpful to have a button that has the opposite function of "Add current site to blacklist". 

With the button "**Remove current site from blacklist**" we could easily unban a site by disabling the Autoclose functionality, going to the site, and remove it from the blacklist with one push of a button.

**Comment by 8176135** [comment]
The problem with this is... wouldn't the add-on automatically close the tab anytime you try to open a site you blacklisted? So you will never get an opportunity to remove the "current" site from the blacklist. 

I do see how having a long list of blacklisted sites could be hard to manage though, what do you think about a filtering/search functionality in the options screen?

**Comment by Chronogram** [comment]
The add-on has the option (button) to temporarily disable the Autoclose functionality. As I mention in my original post.

**Comment by 8176135** [comment]
Ah sorry, don't know how I missed that. 

Yeah, then that is possible. Since multiple rules can apply to one site, I might need to show the user a drop down for them to select which rule to remove.

**Comment by Chronogram** [comment]
Imagine that, when the add-on is disabled (via the big green button) and we are visiting a blacklisted site,  the button **Add current site to blacklist**  changes to **Remove current site from blacklist.** Or, if the entire (sub)domain is blacklisted, the button **Add (sub)domain to blacklist** changes to **Remove (sub)domain from blacklist.** Can it be done?

**Comment by Chronogram** [comment]
bump

**Comment by 8176135** [comment]
Thanks for reminding me, I really need to get around to implementing this.

**Comment by 8176135** [comment]
Done!
