### ISSUE TITLE
Export / import list / migrate with firefox account

### ISSUE THREAD

**Issue by byt3c** [8176135/blacklist-autoclose#13]
I would like to be able to import/export list of blocked sites, and prefereably that this list would sync with otheraddons parameters across firefox account syncing.

**Comment by ChaosOrdeal** [comment]
Yeah, I want to block about 400 websites.  There is simply no way that I'm going to manually type those sites into a text field one by one.  There has got to be a way to import a text/json/csv file of sites to blacklist.  And although I suggest cvs and json, it should just be a flat text file.  Other options don't add any value.

**Comment by 8176135** [comment]
Add import and export function, and moved storage to Firefox's sync storage, so should automatically sync if firefox account is logged in.
