### ISSUE TITLE
Block only triggers on Domain change

### ISSUE THREAD

**Issue by user84918342** [8176135/blacklist-autoclose#19]
Let's say I don't want to see anything on GitHub, except your projects:
```https:\/\/(\w+\.)?github\.com(?!\/8176135)```
This works great and closes the tab if I enter my username in the URL bar or if I click on my profile when searching for it in DuckDuckGo.

What bothers me however is that when I enter GitHub with your URL and then go somewhere else, for example by clicking on my profile picture and then `Your Profile`, I can easily access my own profile, it only closes when I refresh the site.

→ I would expect the tab to close as soon as I enter a blacklisted path, even on the same domain.
Notice that this isn't a problem with GitHub, I just used it as an example.

**Comment by 8176135** [comment]
hmm... I'm pretty sure it's not really a domain change problem, but specific to sites that's a single page app (SPA) like github, where clicking links within github doesn't actually navigate you, but triggers some javascript in the background to redraw the page. 

I'll have to look into if webextensions offers any hooks on URLs being updated by javascript, and blocking on that.

**Comment by user84918342** [comment]
Yes, you are right. I tested it on a static html site and it worked as expected.
I still think this would be extremely useful for social media sites were you don't want to get distracted and just want to see certain accounts, nothing more. Sadly, basically all modern sites use javascript to change paths.

Anyways, [this](https://stackoverflow.com/questions/30464941/detect-tab-url-change-inside-a-firefox-add-on) looks promising.

**Comment by user84918342** [comment]
fixed by #20

**Comment by 8176135** [comment]
Released in v2.2.0
