### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by wvxwxvw** [8176135/blacklist-autoclose#3]
The extension works perfectly with fonts built into the OS. For Example, Candara. It looks almost the same as yours. Should add your own fonts and increase size of addon? In my opinion, this is just unnecessary.

**Comment by 8176135** [comment]
While this is probably true, I don't think the 50kb space that the fonts take up is that big of a deal, even if it is only needed for 1% of OSes to keep everything looking consistent.
