### ISSUE TITLE
No indication of the delay used

### ISSUE THREAD

**Issue by wvxwxvw** [8176135/blacklist-autoclose#6]
No indication of the delay used.
Can add it instead of a placeholder in the delay input field?

**Comment by 8176135** [comment]
Do you mean the fact that close delay time is not shown after refresh? If so, fixed with 23201e021ad9fb273192c122c6f7a6e9845182cd

If not, please reopen this issue and clarify. Thanks!

**Comment by wvxwxvw** [comment]
All is correct.
