### ISSUE TITLE
[bug] Specific addresses are not added

### ISSUE THREAD

**Issue by wvxwxvw** [8176135/blacklist-autoclose#7]
Example:
Disabling scripts in NoScript 
Go to - https://download.cnet.com/NetAnimate/3000-2085_4-75221367.html
Enabling scripts for the top domain
[![](https://i.imgur.com/yFy7BTk.png)](https://i.imgur.com/9hnl0Hf.jpg)
Click "Download Now"
We are redirected to another page
Automatically loading will not work, so click on "restart the download"
A new page opens and the browser download window POPs up
Download the file or close the download window
And now on this empty page, try adding the site to the blacklist, using any of the buttons in the extension menu.
I get this:
[![](https://i.imgur.com/ijwxzlX.png)](https://i.imgur.com/LvYOY1N.jpg)

**Comment by 8176135** [comment]
That's because that page is technically about:blank. The tab never actually loads to the download page, since in Firefox downloads bypasses tabs. Not actually sure how to fix this one.

**Comment by wvxwxvw** [comment]
Yes, I Now checked in the list of closed tabs, this page is not displayed there either.
That is, although the address line contains the page address, but in fact it is about:blank.
What should do about it?
Can you do some kind of checking on the address bar, and not on the actual page address? )

**Comment by wvxwxvw** [comment]
Actually, I don't need about:blank at all, if I want to open some external address from pages, for example about:addons, I will just disable the extension for a while. Perhaps you needlessly blocked this page from being added to the blacklist? It is possible to make it optional?

**Comment by wvxwxvw** [comment]
I disabled the about:blank check and added it to the blacklist. It didn't work. This works for links from about:addons, but not for the page under discussion.

**Comment by 8176135** [comment]
Well the problem is by blocking about:blank, a lot of stuff breaks. Random sites seem to start to automatically close. And ironically, about:blank itself doesn't get closed.

**Comment by wvxwxvw** [comment]
For me, it is closed if the address is explicitly about: blank, as I described above. Or if you call a link from about:addons, for example, from an extension page. There is first the opening of about: blank and only then the address is replaced with the target one. In this case, the extension will still close it, since the timer is already running and it is running with about: blank, and the extension does not check what is on the page at this time.

So I say that the obvious solution would be to check the address bar, not the actual page address.

Of course, maybe I'm wrong, and it won't work that way.

**Comment by 8176135** [comment]
> So I say that the obvious solution would be to check the address bar, not the actual page address.

The problem is the only way I know to get the address bar is the page address via tabs. So I don't know how to go about getting the address bar.

**Comment by wvxwxvw** [comment]
Then the topic can be closed or left open for memory, so that this issue is not raised again.
